# Generated by Django 3.1.2 on 2021-03-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auth_sms'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auth_sms',
            table='auth_sms',
        ),
    ]
